- platform: mqtt
  unique_id: "luce_scale"
  name: "Luce scale"
  state_topic: "shellies/shelly1-BA2205/relay/0"
  command_topic: "shellies/shelly1-BA2205/relay/0/command"
  payload_on: "on"
  payload_off: "off"
  retain: false
  optimistic: false
  qos: 1
