- id: '1554555767326'
  alias: Update dark_sky
  trigger:
  - minutes: /10
    platform: time_pattern
  action:
  - entity_id: sensor.forecast_1
    service: homeassistant.update_entity
  - entity_id: sensor.forecast_2
    service: homeassistant.update_entity
  - entity_id: sensor.forecast_3
    service: homeassistant.update_entity
  - entity_id: sensor.forecast_4
    service: homeassistant.update_entity
  - entity_id: sensor.forecast_5
    service: homeassistant.update_entity
  - entity_id: sensor.forecast_6
    service: homeassistant.update_entity
  - entity_id: sensor.forecast_7
    service: homeassistant.update_entity
- id: '1558901849750'
  alias: Purge DB
  trigger:
  - at: 02:22:22
    platform: time
  condition: []
  action:
  - data:
      keep_days: 7
      repack: 'true'
    service: recorder.purge
  initial_state: true
- id: '1558902673626'
  alias: Update Available Notifications
  trigger:
  - entity_id: binary_sensor.updater
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: Update for Home Assistant is available
    service: notify.notify
