- id: notify_new_ha
  alias: Update Available Notifications
  trigger:
  - entity_id: updater.updater
    platform: state
  action:
  - data:
      message: Update for Home Assistant is available.
    service: notify.ios_mauros_iphone
- id: '1544266085345'
  alias: Lavatrice ON
  trigger:
  - above: '2'
    entity_id: sensor.lavatrice_watts
    platform: numeric_state
  condition:
  - condition: state
    entity_id: input_boolean.washingmachine_status
    state: 'off'
  action:
  - data:
      entity_id: input_boolean.washingmachine_status
    service: input_boolean.turn_on
- id: '1544280061852'
  alias: Lavatrice OFF
  trigger:
  - below: '2'
    entity_id: sensor.lavatrice_watts
    platform: numeric_state
  condition:
  - condition: state
    entity_id: input_boolean.washingmachine_status
    state: 'on'
  action:
  - data:
      entity_id: input_boolean.washingmachine_status
    service: input_boolean.turn_off
  - data_template:
      message: La lavatrice ha finito. Ora puoi stendere il bucato
      title: Bucato Terminato
    service: notify.ios_mauros_iphone
  - data_template:
      message: La lavatrice ha finito. Ora puoi stendere il bucato
      title: Bucato Terminato
    service: notify.ios_grazia_iphone
- id: '1544467402484'
  alias: Lucine ON
  trigger:
  - event: sunset
    offset: -00:45:00
    platform: sun
  condition:
  - condition: state
    entity_id: switch.lucine_casa
    state: 'off'
  action:
  - data:
      entity_id: switch.lucine_casa
    service: switch.turn_on
- id: '1544467476328'
  alias: Lucine OFF
  trigger:
  - event: sunrise
    offset: +00:30:00
    platform: sun
  condition:
  - condition: state
    entity_id: switch.lucine_casa
    state: 'on'
  action:
  - data:
      entity_id: switch.lucine_casa
    service: switch.turn_off
