homeassistant:
  # Name of the location where Home Assistant is running
  name: Casa
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Rome
  # Customization file
  customize: !include_dir_merge_named customize/

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

  auth_providers:
     - type: homeassistant
     - type: legacy_api_password
       api_password: !secret http_api_password

http:
  #api_password: !secret http_api_password
  base_url: !secret base_url
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key

duckdns:
  domain: !secret duckdns_domain 
  access_token: !secret duckdns_token



# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true
  reporting: false

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Sensors
sensor: !include_dir_merge_list sensors/

# Cloud
cloud:

group: !include_dir_merge_named  groups/

#automation: !include_dir_merge_list automations/
automation: !include automations.yaml

#script: !include_dir_merge_named scripts/
script: !include scripts.yaml

media_player:
  - platform: samsungtv
    host: !secret samsungtv_ip
    mac: !secret samsungtv_mac
    name: TV_sala
    port: 8001

alexa_media:
  accounts:
    - email: !secret email_alexa
      password: !secret alexa_password
      url: amazon.it

notify:
  - platform: alexa_media
    name: alexa_media

switch: !include_dir_merge_list switches/

ifttt:
  key: !secret my_ifttt_key

ios:

mqtt:
  discovery: true
  broker: !secret mqtt_broker_IP
  username: !secret mqtt_username
  password: !secret mqtt_password
  client_id: homeassistant
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

device_tracker:
  - platform: bluetooth_tracker
    interval_seconds: 10
    consider_home: 180

deconz:
  host: !secret deconz_ip
  port: 80

input_boolean: !include boolean.yaml


custom_updater:
  component_urls:
    - https://raw.githubusercontent.com/keatontaylor/alexa_media_player/master/custom_components.json
  track:
   - cards
   - components

system_health:

logger:
  default: info
#  logs:
#    pydeconz: debug
#    homeassistant.components.deconz: debug
#    homeassistant.components.mqtt: debug
#    homeassistant.components.switch.tplink: debug
#    homeassistant.components.deconz: debug

