automation:
  name: Automations
  view: yes
  entities:
     - automation.update_available_notifications
     - automation.Lucine_ON
     - automation.Lucine_OFF
     - automation.Lavatrice_OFF
     - automation.lavatrice_on
