binary_sensor:
  - platform: "mqtt"
    state_topic: "zigbee2mqtt/uno"
    availability_topic: "zigbee2mqtt/bridge/state"
    payload_on: true
    payload_off: false
    value_template: "{{ value_json.water_leak }}"
    device_class: "moisture"

sensor:
  - platform: "mqtt"
    state_topic: "zigbee2mqtt/uno"
    availability_topic: "zigbee2mqtt/bridge/state"
    device_class: "battery"
    value_template: "{{ value_json.battery }}"
    json_attributes: 
      - "linkquality"
      - "voltage"
      - "action"
      - "sensitivity"
