- platform: darksky
  name: "dark_sky"
  api_key: !secret dark_sky_api_key
  language: en
  scan_interval:
    days: 0
    hours: 0
    minutes: 10
    seconds: 00
    milliseconds: 0
  monitored_conditions:
    - apparent_temperature_high
    - apparent_temperature_low
    - cloud_cover
    - daily_summary
    - dew_point
    - hourly_summary
    - humidity
    - icon
    - minutely_summary
    - moon_phase
    - ozone
    - precip_accumulation
    - precip_intensity
    - precip_intensity_max
    - precip_probability
    - precip_type
    - pressure
    - summary
    - temperature
    - temperature_high
    - temperature_low
    - uv_index
    - visibility
    - wind_bearing
    - wind_speed
  forecast:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
- platform: template
  sensors:
    forecast_1:
      entity_id: []
      friendly_name_template: >
        {{ ( as_timestamp(now()) + (1 * 86400) ) | timestamp_custom('%A %d %B') }}
      value_template: > 
        {{ states('sensor.dark_sky_icon_1d') }}
      icon_template: >
        {%- set current = states('sensor.dark_sky_icon_1d') %}
        {%- set mapper = {'rain':'pouring', 'cloudy':'cloudy', 'clear-day':'sunny', 'partly-cloudy-day':'partlycloudy', 'partly-cloudy-night':'partlycloudy', 'snow':'snowy', 'fog':'fog', 'wind':'windy'} %}
        {{ 'mdi:weather-'+mapper[current] if current in mapper else 'mdi:help-circle' }} 
    forecast_2:
      entity_id: []
      friendly_name_template: >
        {{ ( as_timestamp(now()) + (2 * 86400) ) | timestamp_custom('%A %d %B') }}
      value_template: > 
        {{ states('sensor.dark_sky_icon_2d') }}
      icon_template: >
        {%- set current = states('sensor.dark_sky_icon_2d') %}
        {%- set mapper = {'rain':'pouring', 'cloudy':'cloudy', 'clear-day':'sunny', 'partly-cloudy-day':'partlycloudy', 'partly-cloudy-night':'partlycloudy', 'snow':'snowy', 'fog':'fog', 'wind':'windy'} %}
        {{ 'mdi:weather-'+mapper[current] if current in mapper else 'mdi:help-circle' }} 
    forecast_3:
      entity_id: []
      friendly_name_template: >
        {{ ( as_timestamp(now()) + (3 * 86400) ) | timestamp_custom('%A %d %B') }}
      value_template: > 
        {{ states('sensor.dark_sky_icon_3d') }}
      icon_template: >
        {%- set current = states('sensor.dark_sky_icon_3d') %}
        {%- set mapper = {'rain':'pouring', 'cloudy':'cloudy', 'clear-day':'sunny', 'partly-cloudy-day':'partlycloudy', 'partly-cloudy-night':'partlycloudy', 'snow':'snowy', 'fog':'fog', 'wind':'windy'} %}
        {{ 'mdi:weather-'+mapper[current] if current in mapper else 'mdi:help-circle' }} 
    forecast_4:
      entity_id: []
      friendly_name_template: >
        {{ ( as_timestamp(now()) + (4 * 86400) ) | timestamp_custom('%A %d %B') }} 
      value_template: > 
        {{ states('sensor.dark_sky_icon_4d') }}
      icon_template: >
        {%- set current = states('sensor.dark_sky_icon_4d') %}
        {%- set mapper = {'rain':'pouring', 'cloudy':'cloudy', 'clear-day':'sunny', 'partly-cloudy-day':'partlycloudy', 'partly-cloudy-night':'partlycloudy', 'snow':'snowy', 'fog':'fog', 'wind':'windy'} %}
        {{ 'mdi:weather-'+mapper[current] if current in mapper else 'mdi:help-circle' }} 
    forecast_5:
      entity_id: []
      friendly_name_template: >
        {{ ( as_timestamp(now()) + (5 * 86400) ) | timestamp_custom('%A %d %B') }}
      value_template: > 
        {{ states('sensor.dark_sky_icon_5d') }}
      icon_template: >
        {%- set current = states('sensor.dark_sky_icon_5d') %}
        {%- set mapper = {'rain':'pouring', 'cloudy':'cloudy', 'clear-day':'sunny', 'partly-cloudy-day':'partlycloudy', 'partly-cloudy-night':'partlycloudy', 'snow':'snowy', 'fog':'fog', 'wind':'windy'} %}
        {{ 'mdi:weather-'+mapper[current] if current in mapper else 'mdi:help-circle' }} 
    forecast_6:
      entity_id: []
      friendly_name_template: >
        {{ ( as_timestamp(now()) + (6 * 86400) ) | timestamp_custom('%A %d %B') }}
      value_template: > 
        {{ states('sensor.dark_sky_icon_6d') }}
      icon_template: >
        {%- set current = states('sensor.dark_sky_icon_6d') %}
        {%- set mapper = {'rain':'pouring', 'cloudy':'cloudy', 'clear-day':'sunny', 'partly-cloudy-day':'partlycloudy', 'partly-cloudy-night':'partlycloudy', 'snow':'snowy', 'fog':'fog', 'wind':'windy'} %}
        {{ 'mdi:weather-'+mapper[current] if current in mapper else 'mdi:help-circle' }} 
    forecast_7:
      entity_id: []
      friendly_name_template: >
        {{ ( as_timestamp(now()) + (7 * 86400) ) | timestamp_custom('%A %d %B') }}
      value_template: > 
        {{ states('sensor.dark_sky_icon_7d') }}
      icon_template: >
        {%- set current = states('sensor.dark_sky_icon_7d') %}
        {%- set mapper = {'rain':'pouring', 'cloudy':'cloudy', 'clear-day':'sunny', 'partly-cloudy-day':'partlycloudy', 'partly-cloudy-night':'partlycloudy', 'snow':'snowy', 'fog':'fog', 'wind':'windy'} %}
        {{ 'mdi:weather-'+mapper[current] if current in mapper else 'mdi:help-circle' }} 
