- platform: miflora
  mac: 'C4:7C:8D:66:25:82'
  name: Flower 1
  force_update: false
  median: 3
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery
 
- platform: miflora
  mac: 'C4:7C:8D:66:46:55'
  name: Flower 2
  force_update: false
  median: 3
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery

#- platform: miflora
#  mac: 'C4:7C:8D:66:25:82'
#  name: Flower 3
#  force_update: false
#  median: 3
#  monitored_conditions:
#    - moisture
#    - light
#    - temperature
#    - conductivity
#    - battery
