- platform: mqtt
  name: "Tensione"
  state_topic: "1694498882.V"
  unit_of_measurement: "V"
  force_update: true
- platform: mqtt
  name: "Corrente"
  state_topic: "1694498882.A"
  unit_of_measurement: "A"
  force_update: true
- platform: mqtt
  name: "Potenza"
  state_topic: "1694498882.W"
  unit_of_measurement: "W"
  force_update: true
- platform: mqtt
  name: "Sfasamento"
  state_topic: "1694498882.PF"
  force_update: true
